---
name: Artifact Test
on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OS: ubuntu-latest
      PYTHON: '3.9'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Package csv files
        uses: actions/upload-artifact@v3
        with:
          name: attack-csv-data-name
          path: |
              attack-csv-data/**
