name: CodeCov
on:
  pull_request:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: ‘1’

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Generate Report
      run: |
        pip install coverage
        coverage run --source src -m unittest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
