name: Super Linter
on:
  pull_request:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          LINTER_RULES_PATH: /
          VALIDATE_ALL_CODEBASE: false
          #DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Keep these validations in sync with the npm run lint script in package.json:
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_MARKDOWN: true
